project:
  type: website
  output-dir: docs

website:
  title: "Sangīt Manjarī"
  page-navigation: true
  search:
    location: navbar
    type: overlay
  navbar:
    background: light
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: Rāgas
        menu:
          - href: rag-adana.qmd
            text: Rāg Āḍānā
          - href: rag-alahiya.qmd
            text: Rāg Ālāhiyā
          - href: rag-bagisvari.qmd
            text: Rāg Bāgīśvarī
          - href: rag-bahar.qmd
            text: Rāg Bahār
          - href: rag-basant.qmd
            text: Rāg Basant
          - href: rag-behag.qmd
            text: Rāg Behāg
          - href: rag-bhairav.qmd
            text: Rāg Bhairav
          - href: rag-bhairavi.qmd
            text: Rāg Bhairavī
          - href: rag-bhimapalasri.qmd
            text: Rāg Bhīmapalaśrī
          - href: rag-bhupali.qmd
            text: Rāg Bhūpāli
          - href: rag-brindabani_sarang.qmd
            text: Rāg Bṛndāvanī sāraṅg
          - href: rag-chayanat.qmd
            text: Rāg Chāyānaṭ
          - href: rag-darabari_kanada.qmd
            text: Rāg Darabāri kānaḍā
          - href: rag-darabari_todi.qmd
            text: Rāg Darabāri toḍī
          - href: rag-gaud_malhar.qmd
            text: Rāg Gauḍ malhār
          - href: rag-hamir.qmd
            text: Rāg Hamīr
          - href: rag-iman_kalyan.qmd
            text: Rāg Iman kalyāṅ
          - href: rag-iman.qmd
            text: Rāg Iman
          - href: rag-kaphi.qmd
            text: Rāg Kāphī
          - href: rag-kedar.qmd
          - text: Rāg Kedār
          - href: rag-megh.qmd
            text: Rāg Megh
          - href: rag-natmalhar.qmd
            text: Rāg Naṭ malhār
          - href: rag-nayaki_kanada.qmd
            text: Rāg Nāyakī kānaḍā
          - href: rag-nisasag.qmd
            text: Rāg Niśāsāg
          - href: rag-purvi.qmd
            text: Rāg Pūrvī
          - href: rag-ramkali.qmd
            text: Rāg Rāmkali
          - href: rag-sarparda.qmd
            text: Rāg Sarpardā  
          - href: rag-sindhu.qmd
            text: Rāg Sindhu
          - href: rag-sukla_belavali.qmd
            text: Rāg Śukla belāvalī
          - href: rag-surat.qmd
            text: Rāg Suraṭ
          - href: rag-syama.qmd
            text: Rāg Śyāma
          - href: rag-tilak_kamod.qmd
            text: Rāg Tilak kāmod
          
    right:
      - icon: github
        href: https://github.com/   # replace with your repo
        aria-label: GitHub
  sidebar: false
    
  page-footer:
    center: |
      © 2025 Society for Indian Music and Arts (SIMA).
      All transliteration content by Dr. Suparno Bhattacharyya.

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true
    toc-location: right
    code-copy: true
    smooth-scroll: true
    anchor-sections: true
    include-in-header:
      - _includes/mathjax-config.html

